version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq-container
    ports:
      - "5673:5672"
      - "15673:15672"

  backend:
    image: phdhuy/load-test-web
    container_name: spring-app-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5673
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq


volumes:
  postgres-data:

