version: '3.8'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    links:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: dockerpassword
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq


volumes:
  postgres-data:

