server:
  servlet:
    context-path: /api
  port:
    8080
spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    mode: HTML
  profiles:
    active: prod
  datasource:
    hikari:
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.pbl.loadpulse.common.config.PostgreSqlCustomDialect
        type: trace
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
auth:
  tokenSecret: 928d4aef-6452-4ca1-8e4e-7dabad510423
  tokenExpirationMsec: 7200000
  refreshTokenSecret: cf427568-e272-4d5d-8195-18cc8bcbd0c4
  refreshTokenExpirationMsec: 2592000000
