spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loadpulse
    username: loadpulse
    password: loadpulse2024
    hikari:
      max-lifetime: 60000
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
  data:
    redis:
      host: redis
      port: 6379
