spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/load-testing
    username: postgres
    password: duchuy
    hikari:
      max-lifetime: 60000
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
