name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          docker stop load-test-web
          docker rm load-test-web
          docker pull phdhuy/load-test-web
          docker run -d --name load-test-web -p 8080:8080 phdhuy/load-test-web